config/routes.rb
Experts::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :topics do
    resources :bailiwicks
  end

  resources :users, only: 'show'

  

end

app/models/bailiwick.rb
class Bailiwick < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  validates_presence_of :user
  validates_presence_of :topic
  validates_presence_of :role
  validates_inclusion_of :role, in: ->(bailiwick) { bailiwick.topic ? bailiwick.topic.available_roles : []}

  scope :with_role, lambda {|role| where(:role => role)}
  scope :with_user, lambda {|user| where(:user => user)}

  @@affinities = %w(noobie seasoned owner)
  validates_presence_of :affinity
  validates_inclusion_of :affinity, :in => @@affinities

  @@ranks = %w(primary secondary)
  validates_presence_of :rank
  validates_inclusion_of :rank, :in => @@ranks

  def self.affinities; @@affinities end
  def self.ranks; @@ranks end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :bailiwicks

  @@role_names = [%w(development), %w(product)]
  def role_names; @@role_names end
  def available_roles; @@role_names.flatten end
end

app/models/topics/component_topic.rb
class ComponentTopic < Topic
end

app/models/topics/integration_topic.rb
class IntegrationTopic < Topic
end

app/models/topics/solution_topic.rb
class SolutionTopic < Topic
end

app/models/topics/technology_topic.rb
class TechnologyTopic < Topic
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate do |user|
    user.must_be_from_domain
  end

  def must_be_from_domain
    return unless Preferences.email_limit_to_domain.present?
    errors.add(:email, "must be from #{Preferences.email_limit_to_domain} domain") unless email =~ Regexp.new(Preferences.email_limit_to_domain)
  end

  validates_presence_of :first_name, :last_name

  def roles
    @roles ||= attributes['roles'] ? YAML::load(attributes['roles']) : []
  end

  def roles= value
    raise ArgumentError, 'Argument is not an Array' unless value.is_a?(Array)
    super(value.to_yaml)
    @roles = value
  end

  has_many :bailiwicks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :initialize_jquery_mobile_page_defaults

  private
  def initialize_jquery_mobile_page_defaults
    @jqm_page_data_role = 'page'
    @jqm_header_data_theme = "a"
  end
end

app/controllers/bailiwicks_controller.rb
class BailiwicksController < ApplicationController
  before_filter :authenticate_user!

  def new
    @topic = Topic.find(params[:topic_id])
    @bailiwick = @topic.bailiwicks.build(:role => params[:role])
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bailiwick = @topic.bailiwicks.build bailiwick_params
    @bailiwick.user = current_user
    if(@bailiwick.save)
      redirect_to(topic_path(@topic))
    else
      render :new
    end
  end

  private
  def bailiwick_params
    return {} unless params[:bailiwick].present?
    params.require(:bailiwick).permit(:rank, :affinity, :role)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def show
    @topic = Topic.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def init_dialog title
    @jqm_page_data_role = 'dialog'
    @jqm_header_data_theme  = 'd'
    content_for :header do raw "<h1>#{title}</h1>" end
  end

  def session_link
    if current_user
      link_to('Logout', destroy_user_session_path, :method => :delete)
    else
      link_to('Login', new_user_session_path, 'data-rel'=>"dialog")
    end
  end

  def error_messages resource
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/bailiwicks_helper.rb
module BailiwicksHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bailiwicks/new.html.haml
= init_dialog "My Expertise in #{@topic.name}"

= form_for @bailiwick, url: topic_bailiwicks_path do |f|
  = error_messages @bailiwick
  %fieldset{'data-role' => 'controlgroup'}
    %legend I would like to be a
    - Bailiwick.ranks.each do |r|
      = f.radio_button :rank, r
      = f.label 'rank_' + r, r

  %fieldset{'data-role' => 'controlgroup'}
    %legend I am a
    - Bailiwick.affinities.each do |a|
      = f.radio_button :affinity, a
      = f.label 'affinity_' + a, a
  = f.hidden_field :role
  = f.submit 'submit'

app/views/home/index.html.haml
- content_for :header do
  %h1
    Experts

= image_tag('hello_expert.jpg')

- content_for :footer do
  - if current_user
    = link_to('Logout', destroy_user_session_path, :method => :delete)
  - else
    = link_to('Login', new_user_session_path, 'data-rel'=>"dialog")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Experts
    <meta name="viewport" content="width=device-width, initial-scale=1">
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
  %body{:class => controller_name + '_controller ' + action_name + '_action' }
    = csrf_meta_tags
    %div{'data-role' => @jqm_page_data_role}
      %div{'data-role' => 'header', 'data-theme' => @jqm_header_data_theme}
        = yield :header
      %div{'data-role' => 'content'}
        - if notice.present?
          %p.notice= notice
        - if alert.present?
          %p.alert= alert
        = yield
      - if @jqm_page_data_role == 'page'
        %div{'data-role' => 'footer', 'class' => 'ui-bar', 'data-position'=>"fixed"}
          = yield :footer

app/views/topics/_bailiwick.html.haml
%li
  = link_to bailiwick.user.first_name + ' ' + bailiwick.user.last_name, user_path(bailiwick.user)

app/views/topics/_role.html.haml
.ui-body.ui-body-d
  %h3
    = role.titleize
  %ul{"data-role"=>"listview", 'data-inset'=>"true"}
    = render :partial => 'bailiwick', :collection => @topic.bailiwicks.with_role(role)
  - if current_user.roles.include?(role) && @topic.bailiwicks.with_user(current_user).count == 0
    = link_to('add me', new_topic_bailiwick_path(@topic, :role => role), 'data-role'=>"button", 'data-icon'=>"plus")

app/views/topics/_topic.html.haml
%li
  %a{:href => topic_path(topic)}
    %h2
      = topic.name

app/views/topics/_user.html.haml
%li
  = link_to(user.email, user_path(user))

app/views/topics/index.html.haml
- content_for :header do
  %h1
    Topics

%ul{"data-role"=>"listview"}
  %li{"data-role"=>"list-divider"} Solution
  = render :partial => 'topic', :collection => SolutionTopic.all
  %li{"data-role"=>"list-divider"} Aspects and Components
  = render :partial => 'topic', :collection => ComponentTopic.all
  %li{"data-role"=>"list-divider"} Integration & External Communication
  = render :partial => 'topic', :collection => IntegrationTopic.all
  %li{"data-role"=>"list-divider"} Technologies
  = render :partial => 'topic', :collection => TechnologyTopic.all

- content_for :footer do
  = session_link

app/views/topics/show.html.haml
- content_for :header do
  %h1
    = @topic.name
.ui-grid-solo
  %h2
    Active Questions
  %ul{"data-role"=>"listview", 'data-inset'=>"true"}
    %li
      Question One


.ui-grid-a
  .ui-block-a
    = render partial: 'role', collection: @topic.role_names.first
  .ui-block-b
    = render partial: 'role', collection: @topic.role_names.last


- content_for :footer do
  = session_link

app/views/users/_bailiwick.html.haml
%li
  = link_to bailiwick.topic.name, topic_path(bailiwick.topic)

app/views/users/show.html.haml
- content_for :header do
  %h1
    = @user.first_name + @user.last_name

.ui-grid-solo
  %h2
    Topics
  %ul{"data-role"=>"listview", 'data-inset'=>"true"}
    = render partial: 'bailiwick', collection: @user.bailiwicks

- content_for :footer do
  = session_link